// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Request struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	List                 bool     `protobuf:"varint,3,opt,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetList() bool {
	if m != nil {
		return m.List
	}
	return false
}

type Reply struct {
	Feedback             string   `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

func init() {
	proto.RegisterType((*File)(nil), "api.File")
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*Reply)(nil), "api.Reply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x1b, 0xbb, 0x5d, 0x37, 0x43, 0x4f, 0x73, 0x5a, 0xf6, 0xb4, 0xa6, 0x08, 0x39, 0x15,
	0xd1, 0x57, 0xa8, 0x82, 0xe0, 0x29, 0xa0, 0xf7, 0xb4, 0x3b, 0x62, 0x30, 0xbb, 0x89, 0x4d, 0x44,
	0xf4, 0x79, 0x7c, 0x50, 0xc9, 0x58, 0xf4, 0xa4, 0xd0, 0xdb, 0x97, 0x7f, 0x92, 0x8f, 0xfc, 0x03,
	0xd2, 0x46, 0xb7, 0x8e, 0xfb, 0x90, 0x03, 0xce, 0x6d, 0x74, 0xea, 0x01, 0xaa, 0x1b, 0xe7, 0x09,
	0x11, 0xaa, 0x68, 0xf3, 0x53, 0x2b, 0x7a, 0xa1, 0xa5, 0x61, 0x2e, 0xd9, 0x64, 0x47, 0x6a, 0x4f,
	0xbe, 0xb3, 0xc2, 0x25, 0x4b, 0xee, 0x83, 0xda, 0x79, 0x2f, 0xf4, 0xc2, 0x30, 0x97, 0x6c, 0xb0,
	0xd9, 0xb6, 0x55, 0x2f, 0xf4, 0xd2, 0x30, 0xab, 0x6b, 0x38, 0x35, 0xf4, 0xf2, 0x4a, 0x29, 0x1f,
	0xa3, 0xf6, 0x2e, 0x65, 0x56, 0x37, 0x86, 0x59, 0xad, 0x60, 0x61, 0x28, 0xfa, 0x77, 0xec, 0xa0,
	0x79, 0x24, 0x1a, 0xb6, 0x76, 0xf7, 0x7c, 0x10, 0xfd, 0x9c, 0x2f, 0x3f, 0x05, 0xc8, 0xdb, 0x29,
	0xd3, 0x7e, 0x17, 0xc6, 0x11, 0x57, 0x50, 0xdf, 0x47, 0x1f, 0xec, 0x80, 0x72, 0x5d, 0xca, 0x96,
	0x7a, 0x1d, 0x30, 0xb2, 0x4a, 0xcd, 0xb4, 0xc0, 0x73, 0x68, 0x36, 0xe1, 0x6d, 0xe2, 0x6b, 0xcb,
	0xc3, 0x8c, 0x7f, 0xdb, 0xfd, 0x3e, 0x52, 0x33, 0x3c, 0x83, 0x7a, 0x43, 0x9e, 0x32, 0xfd, 0xe9,
	0x42, 0x0d, 0xf2, 0xce, 0xa5, 0x5c, 0x26, 0xe9, 0x1f, 0xd5, 0x85, 0xd8, 0xd6, 0xbc, 0xf6, 0xab,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x85, 0x54, 0x96, 0x83, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntercommClient is the client API for Intercomm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntercommClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (Intercomm_UploadClient, error)
	Download(ctx context.Context, in *Request, opts ...grpc.CallOption) (*File, error)
	Delete(ctx context.Context, in *File, opts ...grpc.CallOption) (*Reply, error)
	ListFiles(ctx context.Context, in *Request, opts ...grpc.CallOption) (Intercomm_ListFilesClient, error)
}

type intercommClient struct {
	cc *grpc.ClientConn
}

func NewIntercommClient(cc *grpc.ClientConn) IntercommClient {
	return &intercommClient{cc}
}

func (c *intercommClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Intercomm_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercomm_serviceDesc.Streams[0], "/api.Intercomm/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercommUploadClient{stream}
	return x, nil
}

type Intercomm_UploadClient interface {
	Send(*File) error
	CloseAndRecv() (*Reply, error)
	grpc.ClientStream
}

type intercommUploadClient struct {
	grpc.ClientStream
}

func (x *intercommUploadClient) Send(m *File) error {
	return x.ClientStream.SendMsg(m)
}

func (x *intercommUploadClient) CloseAndRecv() (*Reply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *intercommClient) Download(ctx context.Context, in *Request, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/api.Intercomm/Download", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intercommClient) Delete(ctx context.Context, in *File, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/api.Intercomm/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intercommClient) ListFiles(ctx context.Context, in *Request, opts ...grpc.CallOption) (Intercomm_ListFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercomm_serviceDesc.Streams[1], "/api.Intercomm/ListFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercommListFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Intercomm_ListFilesClient interface {
	Recv() (*File, error)
	grpc.ClientStream
}

type intercommListFilesClient struct {
	grpc.ClientStream
}

func (x *intercommListFilesClient) Recv() (*File, error) {
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntercommServer is the server API for Intercomm service.
type IntercommServer interface {
	Upload(Intercomm_UploadServer) error
	Download(context.Context, *Request) (*File, error)
	Delete(context.Context, *File) (*Reply, error)
	ListFiles(*Request, Intercomm_ListFilesServer) error
}

// UnimplementedIntercommServer can be embedded to have forward compatible implementations.
type UnimplementedIntercommServer struct {
}

func (*UnimplementedIntercommServer) Upload(srv Intercomm_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (*UnimplementedIntercommServer) Download(ctx context.Context, req *Request) (*File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedIntercommServer) Delete(ctx context.Context, req *File) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedIntercommServer) ListFiles(req *Request, srv Intercomm_ListFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}

func RegisterIntercommServer(s *grpc.Server, srv IntercommServer) {
	s.RegisterService(&_Intercomm_serviceDesc, srv)
}

func _Intercomm_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntercommServer).Upload(&intercommUploadServer{stream})
}

type Intercomm_UploadServer interface {
	SendAndClose(*Reply) error
	Recv() (*File, error)
	grpc.ServerStream
}

type intercommUploadServer struct {
	grpc.ServerStream
}

func (x *intercommUploadServer) SendAndClose(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *intercommUploadServer) Recv() (*File, error) {
	m := new(File)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Intercomm_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntercommServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Intercomm/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntercommServer).Download(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Intercomm_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntercommServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Intercomm/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntercommServer).Delete(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _Intercomm_ListFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntercommServer).ListFiles(m, &intercommListFilesServer{stream})
}

type Intercomm_ListFilesServer interface {
	Send(*File) error
	grpc.ServerStream
}

type intercommListFilesServer struct {
	grpc.ServerStream
}

func (x *intercommListFilesServer) Send(m *File) error {
	return x.ServerStream.SendMsg(m)
}

var _Intercomm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Intercomm",
	HandlerType: (*IntercommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _Intercomm_Download_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Intercomm_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Intercomm_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ListFiles",
			Handler:       _Intercomm_ListFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
