// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadReply struct {
	Feedback             string   `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadReply) Reset()         { *m = UploadReply{} }
func (m *UploadReply) String() string { return proto.CompactTextString(m) }
func (*UploadReply) ProtoMessage()    {}
func (*UploadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *UploadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadReply.Unmarshal(m, b)
}
func (m *UploadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadReply.Marshal(b, m, deterministic)
}
func (m *UploadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadReply.Merge(m, src)
}
func (m *UploadReply) XXX_Size() int {
	return xxx_messageInfo_UploadReply.Size(m)
}
func (m *UploadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadReply.DiscardUnknown(m)
}

var xxx_messageInfo_UploadReply proto.InternalMessageInfo

func (m *UploadReply) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type DownloadRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DownloadReply struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadReply) Reset()         { *m = DownloadReply{} }
func (m *DownloadReply) String() string { return proto.CompactTextString(m) }
func (*DownloadReply) ProtoMessage()    {}
func (*DownloadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *DownloadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadReply.Unmarshal(m, b)
}
func (m *DownloadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadReply.Marshal(b, m, deterministic)
}
func (m *DownloadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadReply.Merge(m, src)
}
func (m *DownloadReply) XXX_Size() int {
	return xxx_messageInfo_DownloadReply.Size(m)
}
func (m *DownloadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadReply.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadReply proto.InternalMessageInfo

func (m *DownloadReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DownloadReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DeleteReply struct {
	Feedback             string   `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReply) Reset()         { *m = DeleteReply{} }
func (m *DeleteReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()    {}
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *DeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReply.Unmarshal(m, b)
}
func (m *DeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReply.Marshal(b, m, deterministic)
}
func (m *DeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReply.Merge(m, src)
}
func (m *DeleteReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReply.Size(m)
}
func (m *DeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReply proto.InternalMessageInfo

func (m *DeleteReply) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type ListFilesRequest struct {
	List                 bool     `protobuf:"varint,1,opt,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesRequest) Reset()         { *m = ListFilesRequest{} }
func (m *ListFilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFilesRequest) ProtoMessage()    {}
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ListFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesRequest.Unmarshal(m, b)
}
func (m *ListFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesRequest.Marshal(b, m, deterministic)
}
func (m *ListFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesRequest.Merge(m, src)
}
func (m *ListFilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFilesRequest.Size(m)
}
func (m *ListFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesRequest proto.InternalMessageInfo

func (m *ListFilesRequest) GetList() bool {
	if m != nil {
		return m.List
	}
	return false
}

type ListFilesReply struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesReply) Reset()         { *m = ListFilesReply{} }
func (m *ListFilesReply) String() string { return proto.CompactTextString(m) }
func (*ListFilesReply) ProtoMessage()    {}
func (*ListFilesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ListFilesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesReply.Unmarshal(m, b)
}
func (m *ListFilesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesReply.Marshal(b, m, deterministic)
}
func (m *ListFilesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesReply.Merge(m, src)
}
func (m *ListFilesReply) XXX_Size() int {
	return xxx_messageInfo_ListFilesReply.Size(m)
}
func (m *ListFilesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesReply proto.InternalMessageInfo

func (m *ListFilesReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListFilesReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UploadRequest)(nil), "api.UploadRequest")
	proto.RegisterType((*UploadReply)(nil), "api.UploadReply")
	proto.RegisterType((*DownloadRequest)(nil), "api.DownloadRequest")
	proto.RegisterType((*DownloadReply)(nil), "api.DownloadReply")
	proto.RegisterType((*DeleteRequest)(nil), "api.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "api.DeleteReply")
	proto.RegisterType((*ListFilesRequest)(nil), "api.ListFilesRequest")
	proto.RegisterType((*ListFilesReply)(nil), "api.ListFilesReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0x2a, 0x21, 0x99, 0x5a, 0x2d, 0xa3, 0x42, 0xc9, 0xa9, 0xac, 0x28, 0xe9, 0xa5,
	0x94, 0x7a, 0xb0, 0xe0, 0xb5, 0x08, 0x82, 0xa7, 0x80, 0x0f, 0xb0, 0x6d, 0x46, 0x5c, 0xdc, 0x76,
	0xd7, 0x66, 0x45, 0xfa, 0xc6, 0x3e, 0x86, 0x64, 0x9b, 0xd4, 0x64, 0x0f, 0xc6, 0xde, 0x26, 0xc3,
	0x3f, 0xf3, 0xff, 0xf9, 0x66, 0x21, 0x12, 0x46, 0x8e, 0xcd, 0x46, 0x5b, 0x8d, 0xc7, 0xc2, 0x48,
	0x7e, 0x0f, 0xbd, 0x17, 0xa3, 0xb4, 0xc8, 0x52, 0xfa, 0xf8, 0xa4, 0xdc, 0x22, 0xc2, 0x89, 0x11,
	0xf6, 0x6d, 0xc0, 0x86, 0x2c, 0x89, 0x52, 0x57, 0x17, 0xbd, 0x4c, 0x58, 0x31, 0x38, 0x1a, 0xb2,
	0xe4, 0x34, 0x75, 0x35, 0x1f, 0x41, 0xb7, 0x1a, 0x34, 0x6a, 0x8b, 0x31, 0x84, 0xaf, 0x44, 0xd9,
	0x42, 0x2c, 0xdf, 0xcb, 0xd1, 0xfd, 0x37, 0xbf, 0x81, 0xf3, 0xb9, 0xfe, 0x5a, 0xb7, 0xb8, 0x14,
	0x51, 0x7e, 0x65, 0xc5, 0xce, 0xff, 0x46, 0xb9, 0x86, 0xde, 0x9c, 0x14, 0x59, 0xfa, 0x6b, 0xfb,
	0x08, 0xba, 0x95, 0xa8, 0x2d, 0xef, 0x2d, 0xf4, 0x9f, 0x65, 0x6e, 0x1f, 0xa5, 0xa2, 0xbc, 0xb6,
	0x52, 0xc9, 0xdc, 0x3a, 0x6d, 0x98, 0xba, 0x9a, 0xcf, 0xe0, 0xac, 0xa6, 0x3b, 0x20, 0xf1, 0xf4,
	0x9b, 0x41, 0xf4, 0xb4, 0xb6, 0xb4, 0x59, 0xea, 0xd5, 0x0a, 0xa7, 0x10, 0xec, 0x50, 0x22, 0x8e,
	0x8b, 0xf3, 0x34, 0x0e, 0x12, 0xf7, 0x1b, 0x3d, 0xa3, 0xb6, 0xbc, 0x93, 0x30, 0x9c, 0x41, 0x58,
	0xc1, 0xc2, 0x4b, 0xa7, 0xf0, 0x10, 0xc7, 0xe8, 0x75, 0xdd, 0xe4, 0x84, 0xe1, 0x04, 0x82, 0x1d,
	0x88, 0xd2, 0xad, 0x81, 0xae, 0x74, 0xab, 0x91, 0xe2, 0x1d, 0x7c, 0x80, 0x68, 0xff, 0x9f, 0x78,
	0xe5, 0x04, 0x3e, 0x9f, 0xf8, 0xc2, 0x6f, 0x97, 0x76, 0x8b, 0xc0, 0x3d, 0xb6, 0xbb, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0x0b, 0x30, 0xce, 0x79, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntercommClient is the client API for Intercomm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntercommClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (Intercomm_UploadClient, error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (Intercomm_DownloadClient, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (Intercomm_ListFilesClient, error)
}

type intercommClient struct {
	cc *grpc.ClientConn
}

func NewIntercommClient(cc *grpc.ClientConn) IntercommClient {
	return &intercommClient{cc}
}

func (c *intercommClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Intercomm_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercomm_serviceDesc.Streams[0], "/api.Intercomm/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercommUploadClient{stream}
	return x, nil
}

type Intercomm_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadReply, error)
	grpc.ClientStream
}

type intercommUploadClient struct {
	grpc.ClientStream
}

func (x *intercommUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *intercommUploadClient) CloseAndRecv() (*UploadReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *intercommClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (Intercomm_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercomm_serviceDesc.Streams[1], "/api.Intercomm/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercommDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Intercomm_DownloadClient interface {
	Recv() (*DownloadReply, error)
	grpc.ClientStream
}

type intercommDownloadClient struct {
	grpc.ClientStream
}

func (x *intercommDownloadClient) Recv() (*DownloadReply, error) {
	m := new(DownloadReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *intercommClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, "/api.Intercomm/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intercommClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (Intercomm_ListFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercomm_serviceDesc.Streams[2], "/api.Intercomm/ListFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercommListFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Intercomm_ListFilesClient interface {
	Recv() (*ListFilesReply, error)
	grpc.ClientStream
}

type intercommListFilesClient struct {
	grpc.ClientStream
}

func (x *intercommListFilesClient) Recv() (*ListFilesReply, error) {
	m := new(ListFilesReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntercommServer is the server API for Intercomm service.
type IntercommServer interface {
	Upload(Intercomm_UploadServer) error
	Download(*DownloadRequest, Intercomm_DownloadServer) error
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
	ListFiles(*ListFilesRequest, Intercomm_ListFilesServer) error
}

// UnimplementedIntercommServer can be embedded to have forward compatible implementations.
type UnimplementedIntercommServer struct {
}

func (*UnimplementedIntercommServer) Upload(srv Intercomm_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (*UnimplementedIntercommServer) Download(req *DownloadRequest, srv Intercomm_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedIntercommServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedIntercommServer) ListFiles(req *ListFilesRequest, srv Intercomm_ListFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}

func RegisterIntercommServer(s *grpc.Server, srv IntercommServer) {
	s.RegisterService(&_Intercomm_serviceDesc, srv)
}

func _Intercomm_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntercommServer).Upload(&intercommUploadServer{stream})
}

type Intercomm_UploadServer interface {
	SendAndClose(*UploadReply) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type intercommUploadServer struct {
	grpc.ServerStream
}

func (x *intercommUploadServer) SendAndClose(m *UploadReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *intercommUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Intercomm_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntercommServer).Download(m, &intercommDownloadServer{stream})
}

type Intercomm_DownloadServer interface {
	Send(*DownloadReply) error
	grpc.ServerStream
}

type intercommDownloadServer struct {
	grpc.ServerStream
}

func (x *intercommDownloadServer) Send(m *DownloadReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Intercomm_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntercommServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Intercomm/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntercommServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Intercomm_ListFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntercommServer).ListFiles(m, &intercommListFilesServer{stream})
}

type Intercomm_ListFilesServer interface {
	Send(*ListFilesReply) error
	grpc.ServerStream
}

type intercommListFilesServer struct {
	grpc.ServerStream
}

func (x *intercommListFilesServer) Send(m *ListFilesReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Intercomm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Intercomm",
	HandlerType: (*IntercommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _Intercomm_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Intercomm_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _Intercomm_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListFiles",
			Handler:       _Intercomm_ListFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
